defaults: &defaults
  kingdom: 
    name: Æthelmearc
    adjective: Æthelmearc
    subject: Æthelmearc
    link: http://www.aethelmearc.org
    heralds_link: http://www.aeheralds.net
    maintainer: Dame Elsbeth Anne Roth
  banner: banner.gif

development:
  <<: *defaults
  admin_mail: elsbeth@pobox.com
  submission_mail: jewelherald@aeheralds.net

test:
  <<: *defaults
  admin_mail: elsbeth@pobox.com
  submission_mail: jewelherald@aeheralds.net

production:
  <<: *defaults
  admin_mail: jewelherald@aeheralds.net
  submission_mail: garnetherald@aeheralds.net
